language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pinelliax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pinelliax/docker-react npm run test